name: Deno

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run User Test
        uses: denolib/deno-action@0.19.0
        with:
          args: run user_test.ts --allow-net --allow-env
      - name: Run Gist Test
        uses: denolib/deno-action@0.19.0
        with:
          args: run gist_test.ts --allow-net --allow-env
