name: Deno

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: denolib/setup-deno@master
      - uses: actions/checkout@v1
      - name: Run tests
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} deno test --allow-env --allow-net
